
apiVersion: v1
clusters:
- cluster:
#    certificate-authority-data: 
#    insecure-skip-tls-verify: true
#    server: https://localhost:6443
#    server:  https://localhost:<nodeport>/apis/backup.cv.io/v1/namespaces/default/clusters/local/exec
#    server:  https://loadbalancer/apis/backup.cv.io/v1/namespaces/default/clusters/mycluster1/exec
#    server:  https://localhost:6443/apis/backup.cv.io/v1/namespaces/default/clusters/local/exec
  name: apiserver
contexts:
- context:
    cluster: apiserver
    user: apiserver
  name: apiserver
current-context: apiserver
kind: Config
preferences: {}
users:
- name: apiserver
  user:
    username: apiserver
#    client-certificate-data:
#    client-key-data:
