apiVersion: v1
kind: Service
metadata:
  name: kexer-nodeport
  labels:
    api: kexer
    apiserver: "true"
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    api: kexer
    apiserver: "true"
#  type: LoadBalancer
  type: NodePort
