---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: kexer
  namespace: kexec-system
  labels:
    api: kexer
    apiserver: "true"
data:
  tls.crt: #base64 encoded certificate
  tls.key: #base64 encoded key
